"""Second Brain models.

The brain is provider-independent: embeddings are stored as opaque numeric
vectors and can be generated by any compatible provider. Phase 1 ships a stable
local lexical embedding so the system works without external services.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any
from uuid import uuid4

from gizmo.core.models import now_iso


class BrainMemoryType(str, Enum):
    FACT = "FACT"
    DECISION = "DECISION"
    PREFERENCE = "PREFERENCE"
    LESSON = "LESSON"
    EXPERIENCE = "EXPERIENCE"
    PROJECT_STATE = "PROJECT_STATE"
    TASK = "TASK"
    RESEARCH = "RESEARCH"
    CONVERSATION = "CONVERSATION"
    AGENT_MEMORY = "AGENT_MEMORY"
    RELATIONSHIP = "RELATIONSHIP"
    WARNING = "WARNING"
    IDEA = "IDEA"
    HYPOTHESIS = "HYPOTHESIS"
    EXPERIMENT = "EXPERIMENT"
    EVALUATION = "EVALUATION"
    GOAL = "GOAL"
    PROCEDURE = "PROCEDURE"
    SKILL = "SKILL"


class BrainMemoryStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    ARCHIVED = "ARCHIVED"
    DRAFT = "DRAFT"
    CONFLICTING = "CONFLICTING"


@dataclass
class BrainRelationship:
    source_id: str
    relation: str
    target_id: str
    confidence: float = 0.75
    created_at: str = field(default_factory=now_iso)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class BrainMemory:
    type: BrainMemoryType
    title: str
    content: str
    summary: str
    source: str
    source_agent: str
    project: str = "Gizmo"
    importance: int = 5
    confidence: float = 0.5
    status: BrainMemoryStatus = BrainMemoryStatus.ACTIVE
    tags: list[str] = field(default_factory=list)
    entities: list[str] = field(default_factory=list)
    relationships: list[BrainRelationship] = field(default_factory=list)
    supersedes: list[str] = field(default_factory=list)
    superseded_by: list[str] = field(default_factory=list)
    embedding: list[float] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    id: str = field(default_factory=lambda: f"brain-{uuid4().hex[:12]}")
    created_at: str = field(default_factory=now_iso)
    updated_at: str = field(default_factory=now_iso)
    last_accessed: str | None = None
    access_count: int = 0

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["type"] = self.type.value
        data["status"] = self.status.value
        data["relationships"] = [r.to_dict() if isinstance(r, BrainRelationship) else r for r in self.relationships]
        return data

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "BrainMemory":
        item = dict(data)
        item["type"] = BrainMemoryType(item["type"])
        item["status"] = BrainMemoryStatus(item.get("status", "ACTIVE"))
        item["relationships"] = [BrainRelationship(**rel) for rel in item.get("relationships", [])]
        return cls(**item)
