"""Generic project generator for harmless bootstrap demos."""
from __future__ import annotations

from pathlib import Path


class ProjectGenerator:
    def __init__(self, projects_root: str | Path) -> None:
        self.projects_root = Path(projects_root)
        self.projects_root.mkdir(parents=True, exist_ok=True)

    def create_small_web_app(self, name: str, learned_note: str | None = None) -> dict:
        safe_name = "".join(ch.lower() if ch.isalnum() else "-" for ch in name).strip("-") or "demo-app"
        root = self.projects_root / safe_name
        root.mkdir(parents=True, exist_ok=True)
        title = name.replace("-", " ").title()
        lesson = learned_note or "First run: keep the project dependency-free and testable."
        (root / "index.html").write_text(f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <main class="card">
    <h1>{title}</h1>
    <p>Built by GIZMO bootstrap self-test.</p>
    <p class="lesson">Memory applied: {lesson}</p>
    <button id="pulse">Verify Interaction</button>
    <output id="result">waiting</output>
  </main>
  <script src="app.js"></script>
</body>
</html>
""")
        (root / "styles.css").write_text("""body{margin:0;min-height:100vh;display:grid;place-items:center;font-family:system-ui;background:#0b1020;color:#eef}.card{max-width:640px;padding:32px;border:1px solid #334;border-radius:24px;background:#111936;box-shadow:0 20px 70px #0008}.lesson{color:#8ee6c4}button{padding:12px 16px;border:0;border-radius:12px;background:#8ee6c4;color:#071018;font-weight:700}output{display:block;margin-top:16px;color:#f6d365}
""")
        (root / "app.js").write_text("""document.getElementById('pulse').addEventListener('click',()=>{document.getElementById('result').textContent='interaction verified';});
""")
        (root / "README.md").write_text(
            f"# {title}\n\nGenerated by GIZMO self-test.\n\nLesson applied: {lesson}\n"
        )
        return {"name": safe_name, "root": str(root), "files": ["index.html", "styles.css", "app.js", "README.md"]}
